### ISSUE TITLE
App crashes after executing findLocalDevices

### ISSUE THREAD

**Issue by arys** [DylanPiercey/local-devices#38] opened 2021-03-18 05:59 UTC
Hello everyone, I have app that scans devices in local network, and when i am trying to use this lib app crashes.
I found out that `getServers()` function returns too many servers. In my case:
```
[
  '25.0.0.2', '25.0.0.3', '25.0.0.4', '25.0.0.5', '25.0.0.6',
  '25.0.0.7', '25.0.0.8', '25.0.0.9', '25.0.0.10', '25.0.0.11',
  '25.0.0.12', '25.0.0.13', '25.0.0.14', '25.0.0.15', '25.0.0.16',
  '25.0.0.17', '25.0.0.18', '25.0.0.19', '25.0.0.20', '25.0.0.21',
  '25.0.0.22', '25.0.0.23', '25.0.0.24', '25.0.0.25', '25.0.0.26',
  '25.0.0.27', '25.0.0.28', '25.0.0.29', '25.0.0.30', '25.0.0.31',
  '25.0.0.32', '25.0.0.33', '25.0.0.34', '25.0.0.35', '25.0.0.36',
  '25.0.0.37', '25.0.0.38', '25.0.0.39', '25.0.0.40', '25.0.0.41',
  '25.0.0.42', '25.0.0.43', '25.0.0.44', '25.0.0.45', '25.0.0.46',
  '25.0.0.47', '25.0.0.48', '25.0.0.49', '25.0.0.50', '25.0.0.51',
  '25.0.0.52', '25.0.0.53', '25.0.0.54', '25.0.0.55', '25.0.0.56',
  '25.0.0.57', '25.0.0.58', '25.0.0.59', '25.0.0.60', '25.0.0.61',
  '25.0.0.62', '25.0.0.63', '25.0.0.64', '25.0.0.65', '25.0.0.66',
  '25.0.0.67', '25.0.0.68', '25.0.0.69', '25.0.0.70', '25.0.0.71',
  '25.0.0.72', '25.0.0.73', '25.0.0.74', '25.0.0.75', '25.0.0.76',
  '25.0.0.77', '25.0.0.78', '25.0.0.79', '25.0.0.80', '25.0.0.81',
  '25.0.0.82', '25.0.0.83', '25.0.0.84', '25.0.0.85', '25.0.0.86',
  '25.0.0.87', '25.0.0.88', '25.0.0.89', '25.0.0.90', '25.0.0.91',
  '25.0.0.92', '25.0.0.93', '25.0.0.94', '25.0.0.95', '25.0.0.96',
  '25.0.0.97', '25.0.0.98', '25.0.0.99', '25.0.0.100', '25.0.0.101',
  ... 16777364 more items
]
```
Maybe we should add limit to `gerServers()` response size?

I use electron 12.0.1 on windows 10, local-devices lib version: 3.1.0

**Comment by thegamerx1** [comment] 2021-04-19 16:18
my app is crashing exactly when running `find()`

**Comment by DylanPiercey** [comment] 2022-08-17 20:05
duplicate of https://github.com/DylanPiercey/local-devices/issues/52

**Closed by DylanPiercey** 2022-08-17 20:05 UTC
