### ISSUE TITLE
Arp -a table for react-native?

### ISSUE THREAD

**Issue by Eduardo-Maia98** [DylanPiercey/local-devices#29] opened 2020-05-05 22:56 UTC
Hi, i'm doing a RN project, and I want to create a arp table of the local network , this libary is perfect for me, but it works on react-native?
Sorry, I'm a layman in this regard

**Comment by RichardRNStudio** [comment] 2020-10-27 17:46
Hi, I would like to use this package with React Native as well, do you have any updates?

**Comment by DylanPiercey** [comment] 2022-08-12 15:25
Duplicate of https://github.com/DylanPiercey/local-devices/issues/58 (although your issue was first)

**Closed by DylanPiercey** 2022-08-12 15:25 UTC
