### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by johan44co** [DylanPiercey/local-devices#55] opened 2022-03-29 23:51 UTC
I got the current error on MacBook Air 2020 8GB macOS Monterrey 12.2.1
It use to work correctly
Is somebody else with a similar issue?
Apparently, this error happens just with large networks.

```
> require("local-devices")()

<--- Last few GCs --->

[40704:0x160008000]    38829 ms: Scavenge (reduce) 2047.0 (2076.7) -> 2046.7 (2077.5) MB, 49.9 / 0.0 ms  (average mu = 0.384, current mu = 0.398) allocation failure 
[40704:0x160008000]    40469 ms: Mark-sweep (reduce) 2047.9 (2077.7) -> 2047.4 (2078.2) MB, 1561.2 / 2.5 ms  (+ 117.5 ms in 30 steps since start of marking, biggest step 6.8 ms, walltime since start of marking 1757 ms) (average mu = 0.314, current mu = 0.

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10028446c node::Abort() [/usr/local/bin/node]
 2: 0x1002845f4 node::errors::TryCatchScope::~TryCatchScope() [/usr/local/bin/node]
 3: 0x1003d27b4 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x1003d2748 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x100555c08 v8::internal::Heap::GarbageCollectionReasonToString(v8::internal::GarbageCollectionReason) [/usr/local/bin/node]
 6: 0x100554728 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x10055fa04 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 8: 0x10055fa98 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0x100532950 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
10: 0x100867d10 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
11: 0x100b7c2ec Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
12: 0x100bc2b48 Builtins_PromiseConstructor [/usr/local/bin/node]
13: 0x100b0d1b0 Builtins_JSBuiltinsConstructStub [/usr/local/bin/node]
14: 0x104d1bd24 
15: 0x100b98788 Builtins_ArrayMap [/usr/local/bin/node]
16: 0x100b0ff78 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
17: 0x100b0ff78 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
18: 0x100b0ff78 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
19: 0x100b0dd6c Builtins_JSEntryTrampoline [/usr/local/bin/node]
20: 0x100b0da04 Builtins_JSEntry [/usr/local/bin/node]
21: 0x1004e2488 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
22: 0x1004e1b1c v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/usr/local/bin/node]
23: 0x1003da39c v8::Script::Run(v8::Local<v8::Context>) [/usr/local/bin/node]
24: 0x10027a894 node::contextify::ContextifyScript::EvalMachine(node::Environment*, long long, bool, bool, bool, std::__1::shared_ptr<v8::MicrotaskQueue>, v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
25: 0x10027a494 node::contextify::ContextifyScript::RunInThisContext(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
26: 0x10043f57c v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
27: 0x10043f074 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
28: 0x10043e900 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
29: 0x100b7c42c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
30: 0x100b0ff78 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
31: 0x100b0ff78 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
32: 0x100b0ff78 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
33: 0x100b0ff78 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
34: 0x100b0ff78 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
35: 0x104ca1e78 
36: 0x104ca71b4 
37: 0x100b0ff78 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
38: 0x100b0ff78 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
39: 0x104ca5f28 
40: 0x104ca2ec8 
41: 0x104c9e77c 
42: 0x104ca1cd0 
43: 0x104ca71b4 
44: 0x104cac604 
45: 0x100b4174c Builtins_GeneratorPrototypeNext [/usr/local/bin/node]
46: 0x104ca097c 
47: 0x104ca1cd0 
48: 0x104ca71b4 
49: 0x104cbb940 
50: 0x104cca720 
51: 0x104caf660 
52: 0x104ccd458 
53: 0x104c94afc 
54: 0x100b0dd6c Builtins_JSEntryTrampoline [/usr/local/bin/node]
55: 0x100b0da04 Builtins_JSEntry [/usr/local/bin/node]
56: 0x1004e2488 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
57: 0x1004e1b1c v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/usr/local/bin/node]
58: 0x1003ef0c0 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/usr/local/bin/node]
59: 0x1001d4348 node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
60: 0x1001e94ac node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/usr/local/bin/node]
61: 0x10032a474 node::StreamBase::CallJSOnreadMethod(long, v8::Local<v8::ArrayBuffer>, unsigned long, node::StreamBase::StreamBaseJSChecks) [/usr/local/bin/node]
62: 0x10032c440 node::EmitToJSStreamListener::OnStreamRead(long, uv_buf_t const&) [/usr/local/bin/node]
63: 0x100330a60 node::LibuvStreamWrap::OnUvRead(long, uv_buf_t const*) [/usr/local/bin/node]
64: 0x100afb704 uv__stream_io [/usr/local/bin/node]
65: 0x100b03824 uv__io_poll [/usr/local/bin/node]
66: 0x100af1fa0 uv_run [/usr/local/bin/node]
67: 0x1001d4e00 node::SpinEventLoop(node::Environment*) [/usr/local/bin/node]
68: 0x1002bd638 node::NodeMainInstance::Run(int*, node::Environment*) [/usr/local/bin/node]
69: 0x1002bd304 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [/usr/local/bin/node]
70: 0x1002562ec node::Start(int, char**) [/usr/local/bin/node]
71: 0x104a6d0f4 
zsh: abort      node
```

**Comment by DylanPiercey** [comment] 2022-08-17 20:05
duplicate of https://github.com/DylanPiercey/local-devices/issues/52

**Closed by DylanPiercey** 2022-08-17 20:05 UTC
